# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t03_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='describe',
            field=models.TextField(max_length=1000, null=True, verbose_name='描述'),
        ),
    ]
