# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t03', '0004_authoe_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authoe',
            new_name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='t03.Author', verbose_name='作者'),
        ),
    ]
