# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t03', '0006_boy_girl'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuoJiCheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('height', models.FloatField(verbose_name='身高')),
                ('suibian', models.IntegerField(null=True)),
                ('salsry', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
