# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t07', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
    ]
