# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t07', '0002_auto_20180820_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='家庭')),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '人'},
        ),
        migrations.AddField(
            model_name='person',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t07.Home'),
        ),
    ]
