# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t06', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='iconurl',
            field=models.CharField(max_length=255, null=True, verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '男女')], verbose_name='性别'),
        ),
    ]
