# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('age', models.IntegerField()),
                ('sexy', models.CharField(max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('is_married', models.BooleanField(default=False, verbose_name='是否已婚')),
            ],
            options={
                'verbose_name': ('个人信息',),
                'db_table': 'person_imformation',
            },
        ),
    ]
